### ISSUE TITLE
Minor recommended edit of blog post

### ISSUE THREAD

**Issue by ghost** [statcompute/MonotonicBinning#1]
Hi,

There was no facility for comments at the 10th March 2019 blog post, so I resorted to leaving the comment here. 

The Tibshirani and Knight paper cited in the post as Tibshirani and Knight, 1997, is actually Tibshirani and Knight, 1999. See https://www.tandfonline.com/doi/abs/10.1080/10618600.1999.10474842

That's it!

Toodles,

 -- Jan Galkowski, https://667-per-cm.net

**Comment by statcompute** [comment]
Check http://statweb.stanford.edu/~tibs/ftp/bumping.ps and I think I am
correct.
