### ISSUE TITLE
parallel::mclapply

### ISSUE THREAD

**Issue by VladPerervenko** [statcompute/MonotonicBinning#2]
`batch_bin(df, 1) -> qtl
Error in parallel::mclapply(xnames, mc.cores = parallel::detectCores(), : 'mc.cores' > 1 is not supported on Windows`
There are many other parallelization capabilities running on all platforms.

**Comment by statcompute** [comment]
That is the issue related to Windows. This piece of code should work fine in Ubuntu or alike.

**Comment by statcompute** [comment]
> `batch_bin(df, 1) -> qtl Error in parallel::mclapply(xnames, mc.cores = parallel::detectCores(), : 'mc.cores' > 1 is not supported on Windows`
> There are many other parallelization capabilities running on all platforms.
I do not have a windows machine with R installed. Is foreach() working for all OS?

**Comment by statcompute** [comment]
I do not have a windows machine with R installed. Is foreach() working for all OS?

**Comment by VladPerervenko** [comment]
Yes, but better with package "doFuture".

**Comment by VladPerervenko** [comment]
Maybe it's better not to do **batch_bin** separately? For each function, provide the ability to calculate the required number of columns. Additional parameter - parallel calculation. Take a look dplyr::ddply(), dlply()...

**Comment by statcompute** [comment]
parallel functions that support socket should solve the problem of not running on windows. I am going to update the code.

**Comment by statcompute** [comment]
changed the forking to the socket in batch_bin() and batch_woe() functions.
