### ISSUE TITLE
install package

### ISSUE THREAD

**Issue by diegoib** [statcompute/MonotonicBinning#3]
Hi WenSui Liu! How can I install your package from R? Thanks

**Comment by statcompute** [comment]
Since this is still considered unpublished, you can just simply source my code. By the way, thanks for asking.

**Comment by statcompute** [comment]
> Hi WenSui Liu! How can I install your package from R? Thanks

Please feel free to let me know if you still have any issue for using these functions?

**Comment by VladPerervenko** [comment]
Collect all functions in one file, for example MOB.R.
place it in any directory, for example C:/RData.
In scripts you use so
`install_packages(import)
import::from("C:/RData/MOB.R",  bad_bin, manual_bin) `

**Comment by statcompute** [comment]
In a section in the project page. 
https://github.com/statcompute/MonotonicBinning/blob/master/README.MD#installation
