### ISSUE TITLE
add binning algorithms reference

### ISSUE THREAD

**Issue by transposition** [statcompute/MonotonicBinning#5]
Thank you for you nice work ! But i'm not familiar with R and those  binning algorithms .
So, can you give some detail paper or other reference ?

**Comment by statcompute** [comment]
thanks for trying to understand my package.
for the reference of R, you might take a look at www.r-project.org.
for the reference of using monotonic binning in the consumer credit risk scorecard, there are multiple books that you can get started. The book "Credit Risk Scorecards" by Naeem Siddiqi is a good one.
