### ISSUE TITLE
readRDS

### ISSUE THREAD

**Issue by VladPerervenko** [statcompute/MonotonicBinning#7]
`> require(mob)
Загрузка требуемого пакета: mob
> df <- readRDS("df.rds") 
Ошибка в gzfile(file, "rb") :не могу открыть соединение
Вдобавок: Предупреждение:
В gzfile(file, "rb") :
  не могу открыть сжатый файл 'df.rds', возможная причина -- 'No such file or directory'`
  _Add the date folder to the compressed file_

**Comment by statcompute** [comment]
Could you please translate the issue into English? Thanks.
